name: Sample CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-sample-app
      PROJECT_ID: dummy-project
      REGISTRY_URL: eu.gcr.io # You might need to change this
      HUMANITEC_ORG: nils-test-org # Make sure to change this

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Inform Humanitec about new image
      - name: Inform Humanitec
        run: |-
          echo Branch:$GITHUB_REF_NAME, Commit:$GITHUB_SHA, Image:$REGISTRY_URL/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA, Tags:$GITHUB_SHA &&\
          curl \
            --request POST 'https://api.humanitec.io/orgs/'$HUMANITEC_ORG'/images/'$IMAGE_NAME'/builds' \
            --header 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "branch": "'$GITHUB_REF_NAME'",
                "commit": "'$GITHUB_SHA'",
                "image": "'$REGISTRY_URL/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA'",
                "tags": ["'$GITHUB_SHA'"]
            }' -v